export const Categories=[
    {
        id:1,
        title:"Clothing",
        img:"https://source.unsplash.com/user/erondu/800x400" 
    },
    {
        id:2,
        title:"Electronics",
        img:"https://source.unsplash.com/user/jackie/800x400" 
},
    { 
    id:3,
    title:"Shoes",
    img:""
},
    {id:4,
    title:"Grocery",
    img:""},
    {id:5,
    title:"Equipments",
    img:""},
    {id:6,
        title:"Mens",
        img:""
    }]